# Generated by Django 5.2.7 on 2025-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('followed_by_viewer', models.BooleanField(default=False)),
                ('requested_by_viewer', models.BooleanField(default=False)),
                ('profile_url', models.URLField()),
            ],
        ),
    ]
